gpn-prototypes/vega-rb

- .github/kuberta.yaml
- .github/workflows/build-static.yaml
> VEGA-446: Настроить деплой vega-rb

- jest.config.js
- package.json
- yarn.lock
> jest-junit test reporter dependency added (dev scope)

- src/App.css
- src/App.tsx
- src/components/Providers/Providers.tsx
- src/index.tsx
Reverts gpn-prototypes/vega-rb#34
> Revert "VEGA-672: Заменить роутер в vega-shell"

- ci/Jenkinsfile-gpn
> GPN CI Jenkinsfile added

- ci/Jenkinsfile-gpn
> GPN CI Jenkinsfile added (to integration)

- ci/Jenkinsfile-gpn
> Added linters stage

- ci/Jenkinsfile-gpn
> Added linters stage (integration)

- ci/Jenkinsfile-gpn
> Added CI env flag

- src/components/DistributionSettings/data.ts
> VEGA-1473: Вывод "непроцентильных" способов задания логнормального распределения

- src/components/DistributionSettings/DistributionSettingsForm/data.ts
- src/components/DistributionSettings/DistributionSettingsForm/getInputStyleType.ts
- src/components/DistributionSettings/data.ts
> VEGA-1473, VEGA-2418: откатил изменения 

- src/components/DistributionSettings/DistributionSettingsForm/data.ts
- src/components/DistributionSettings/data.ts
- src/components/ExcelTable/Models/GridColumnEntity.ts
- src/components/ExcelTable/types.ts
- src/components/HierarchyLevelList/HierarchyLevelItem/data.ts
- src/pages/Scheme/components/Table/queries.ts
- src/types.ts
- src/utils/packTableData.ts
- src/utils/unpackTableData.ts
Исравил ошибку связанну с отображением параметров видимости в контроле Настройка уровней иерархии
JIRA: https://jira.konakov.tv/browse/VEGA-2891
Стенд: http://rlunev-nd-vega-builder.code013.org/
> VEGA-2891:  исравил ошибку связанну с отображением параметров видимости

- src/components/ExcelTable/Models/GridColumnEntity.ts
- src/components/ExcelTable/types.ts
- src/components/HierarchyLevelList/HierarchyLevelItem/data.ts
- src/pages/Scheme/components/Table/queries.ts
- src/types.ts
- src/utils/packTableData.ts
- src/utils/unpackTableData.ts
This reverts commit d44bfe6355f60d0d3ef8dc703ed13aab6268d901, reversing
changes made to 0f7596cbd70624498a08e6b754b06afff03fb15d.
> Revert "Merge pull request #62 from gpn-prototypes/VEGA-2891"

- src/services/ProjectService.ts
- src/types.ts
> [HOTFIX] Исправил 401 ошибку при запросе файла с расчетом

- src/pages/Scheme/Scheme.module.css
> [Alpha][VEGA-2609]: поправил верстку панели с формой для расчета распределений

- src/components/ExcelTable/StyledRow/StyledRow.css
- src/components/ExcelTable/StyledRow/StyledRow.tsx
- src/components/TableErrorAlert/TableErrorAlert.css
- src/components/TableErrorAlert/TableErrorAlert.tsx
- src/components/TableErrorAlert/cn-table-error-alert.ts
- src/components/TableErrorAlert/index.ts
- src/pages/Scheme/Scheme.tsx
- src/pages/Scheme/components/CalculateButton/CalculateButton.tsx
- src/utils/assembleErrors.ts
Стенд: http://rlunev-nd-vega-builder.code013.org/
Задача: https://jira.konakov.tv/browse/VEGA-2908
> [Alpha][VEGA-2908]: Добавил оповещение и выделение для ошибок в строке таблицы

- .graphqlconfig
- codegen.project.dev.yml
- package.json
- schemas/default.graphql
- schemas/project.graphql
- src/components/ExcelTable/Cells/CellWithError.tsx
- src/components/ExcelTable/Columns/renderColumns.tsx
- src/components/ExcelTable/ExcelTable.tsx
- src/components/ExcelTable/Header/DefaultHeader/DefaultHeader.tsx
- src/components/ExcelTable/Header/DraggableHeader/DraggableHeader.tsx
- src/components/ExcelTable/Header/Header.module.css
- src/components/ExcelTable/Header/getHeaderComponent.ts
- src/components/ExcelTable/Input/Input.module.css
- src/components/ExcelTable/helpers.ts
- src/components/ExcelTable/types.ts
- src/components/ExcelTable/utils/columns/__mocks__/columnsList.ts
- src/components/ExcelTable/utils/columns/getSameColumnKeys.test.ts
- src/components/ExcelTable/utils/columns/getSameColumnKeys.ts
- src/components/TableErrorAlert/TableErrorAlert.tsx
- src/generated/graphql.tsx
- src/hooks/index.ts
- src/hooks/useCombinedRefs.ts
- src/hooks/useUpdateErrors.ts
- src/types.ts
- src/utils/__mocks__/tableErrorsList.ts
- src/utils/assembleErrors.test.ts
- src/utils/assembleErrors.ts
 Добавить подсветку и всплывающий тултип для колонок с одинаковыми именами
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/125/
_{Screenshot}_
> fix[VEGA-3043]+[VEGA-2984]: Не отображается ошибка у дублирующихся столбцов

- src/components/ExcelTable/ExcelTable.tsx
- src/components/ExcelTable/StyledRow/StyledRow.tsx
- src/pages/Scheme/Scheme.tsx
- src/pages/Scheme/components/Table/Table.tsx
- src/services/ProjectService.ts
- src/services/loadTableData.ts
Не скрывается контрол с распределением, при переходе к заполнению категорий
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/141/
> fix[VEGA-2979]: Не скрывается форма распределения, при активации категорий

- src/components/DistributionSettings/data.ts
Привести подписи параметров для задания распределений в валидное состояние
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/204/
_{Screenshot}_
_{Screenshot}_
_{Screenshot}_
> fix(VEGA-3171): Привести параметры распределений в валидное состояние

- schemas/default.graphql
- schemas/project.graphql
- src/generated/graphql.tsx
- src/pages/Scheme/components/Table/queries.ts
- src/pages/Scheme/mutations.ts
Удалить поле "column" из типа TableError и всей связанной логики, поправить тесты.
Это поле больше не представляет интереса, т.к. используется "columnKey".
https://jira.vegaspace.tk/browse/VEGA-3278
https://jira.vegaspace.tk/browse/VEGA-1462
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/263/
_{Screenshot}_
_{Screenshot}_
> refactor(VEGA-3279): Удалить поле column из TableError

- src/components/DistributionSettings/DistributionChart/DistributionChart.css
- src/components/DistributionSettings/DistributionSettings.tsx
- src/components/DistributionSettings/DistributionSettingsForm/DistributionSettingsForm.tsx
- src/components/DistributionSettings/DistributionSettingsFormField/DistributionSettingsFormField.tsx
- src/components/DistributionSettings/DistributionSettingsFormField/types.ts
- src/components/DistributionSettings/helpers.ts
- src/components/DistributionSettings/types.ts
- src/components/ExcelTable/Cells/CellWithError.tsx
- src/components/ExcelTable/types.ts
- src/pages/Scheme/components/Table/queries.ts
- src/services/ProjectService.ts
- src/types.ts
добавить усечение мин/макс для распределений
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/231/
> [VEGA-3172]: добавить усечение мин/макс для распределений

- .env.example
- .graphqlconfig
- .huskyrc.js
- package.json
- schemas/default.graphql
- schemas/project.graphql
- src/__mocks__/domainObjects.ts
- src/__mocks__/projectStructure.ts
- src/components/ExcelTable/ContextMenu/HeaderContextMenu.tsx
- src/components/ExcelTable/ContextMenu/RowContextMenu.tsx
- src/components/ExcelTable/ExcelTable.tsx
- src/components/ExcelTable/StyledRow/StyledRow.tsx
- src/components/ExcelTable/types.ts
- src/generated/graphql.tsx
- src/hooks/useUpdateErrors.ts
- src/pages/Scheme/components/CalculateButton/CalculateButton.tsx
- src/pages/Scheme/components/Table/queries.ts
- src/services/ProjectService.ts
- src/types.ts
- src/utils/packTableData.ts
- src/utils/packagingTableData/assembleDomainObjects.test.ts
- src/utils/packagingTableData/assembleDomainObjects.ts
- src/utils/unpackTableData.ts
- src/utils/unpackingData/collectors.ts
- src/utils/unpackingData/constructRows.test.ts
- src/utils/unpackingData/constructRows.ts
- src/utils/unpackingData/index.ts
- yarn.lock
- Добавить возможность удаления строк (используется контекстное меню)
- Имя скачиваемого архива с результатами расчета должен определять бэкенд
[VEGA-2652](https://jira.vegaspace.tk/browse/VEGA-2652)
[VEGA-3281](https://jira.vegaspace.tk/browse/VEGA-3281)
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/328/
> [VEGA-2652][VEGA-3281] Удаление строк, изменение имени архива с расчетами

- src/__mocks__/tableState.ts
- src/components/ExcelTable/Cells/CellWithError.tsx
- src/components/ExcelTable/StyledRow/StyledRow.tsx
- src/pages/Scheme/components/TreeEditor/helpers.ts
- src/store/errorsDuck.ts
- src/store/tableDuck.test.ts
- src/store/tableDuck.ts
- src/utils/getRowId.ts
исправил индексацию ошибок
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND%20TOOLBOX/job/scenario-tests-on-demand/366
_{Screenshot}_
> [VEGA-3378]: исправил индексацию ошибок

- .gitignore
- src/components/DistributionSettings/queries.ts
- src/generated/graphql.tsx
- src/pages/Scheme/components/CalculateButton/CalculateButton.tsx
- src/pages/Scheme/components/Table/Table.tsx
- src/pages/Scheme/components/Table/queries.ts
- src/pages/Scheme/mutations.ts
- src/services/ProjectService.ts
- src/store/tableDuck.ts
Jira issue: VEGA-2854
_{link}_
_{Screenshot}_
_{Screenshot}_
_{Screenshot}_
> [VEGA-2854] [FE] Переинтегрироваться с бэком РБ в части решения ошибки конфликтов версий

- jest.config.js
Удален JUnit-репортер для задачи тестирования по-умолчанию, т.к. из-за этого все тесты стали гораздо дольше выполняться
_{link}_
_{Screenshot}_
_{Screenshot}_
_{Screenshot}_
> chore(Jest): Удален запуск JUnit-репортера для тестов по-умолчанию

- ci/build.sh
Игнор ошибок при удалении докера
_{link}_
_{Screenshot}_
_{Screenshot}_
_{Screenshot}_
> [VEGA-3243] ci: Исправление общей сборки на YC
